// Generated by scripts/build_tz_table.py. Do not edit.
#pragma once

#include <cstddef>

namespace data {

struct TzPosix {
  const char* iana;   // e.g. "America/Toronto"
  const char* posix;  // e.g. "EST5EDT,M3.2.0,M11.1.0"
};

/** Sorted by iana (strcmp order). */
extern const TzPosix kTzPosix[];
extern const size_t kTzPosixCount;

}  // namespace data
