#!/usr/bin/env python3
"""Build the IANA time zone -> POSIX TZ string table for the clock.

Every TZif (v2+) file ends with a POSIX TZ footer describing the zone's current rule,
including DST. This reads those footers from the `tzdata` package and writes
include/data/tz_posix.h and src/data/tz_posix_data.cpp, sorted by name for a binary search.

Requires: pip install tzdata
"""

from __future__ import annotations

from importlib import resources
from pathlib import Path

import tzdata

ROOT = Path(__file__).resolve().parents[1]
HEADER = ROOT / "include" / "data" / "tz_posix.h"
SOURCE = ROOT / "src" / "data" / "tz_posix_data.cpp"


def zone_names() -> list[str]:
    zones = resources.files("tzdata").joinpath("zones").read_text(encoding="utf-8")
    return [z.strip() for z in zones.splitlines() if z.strip()]


def posix_footer(name: str) -> str | None:
    data = resources.files("tzdata.zoneinfo").joinpath(*name.split("/")).read_bytes()
    if not data.startswith(b"TZif") or data[4:5] in (b"\0", b""):
        return None  # v1 files have no footer
    footer = data.rstrip(b"\n").rsplit(b"\n", 1)[-1].decode("ascii")
    return footer or None


def main() -> None:
    rows = []
    for name in zone_names():
        tz = posix_footer(name)
        if tz:
            rows.append((name, tz))
    rows.sort()

    HEADER.parent.mkdir(parents=True, exist_ok=True)
    HEADER.write_text(
        "// Generated by scripts/build_tz_table.py. Do not edit.\n"
        "#pragma once\n\n"
        "#include <cstddef>\n\n"
        "namespace data {\n\n"
        "struct TzPosix {\n"
        "  const char* iana;   // e.g. \"America/Toronto\"\n"
        "  const char* posix;  // e.g. \"EST5EDT,M3.2.0,M11.1.0\"\n"
        "};\n\n"
        "/** Sorted by iana (strcmp order). */\n"
        "extern const TzPosix kTzPosix[];\n"
        "extern const size_t kTzPosixCount;\n\n"
        "}  // namespace data\n",
        encoding="utf-8",
        newline="\n",
    )

    lines = [
        f"// Generated by scripts/build_tz_table.py from tzdata {tzdata.IANA_VERSION}. "
        "Do not edit.",
        '#include "data/tz_posix.h"',
        "",
        "namespace data {",
        "",
        "const TzPosix kTzPosix[] = {",
    ]
    lines += [f'    {{"{name}", "{tz}"}},' for name, tz in rows]
    lines += [
        "};",
        "",
        "const size_t kTzPosixCount = sizeof(kTzPosix) / sizeof(kTzPosix[0]);",
        "",
        "}  // namespace data",
        "",
    ]
    SOURCE.write_text("\n".join(lines), encoding="utf-8", newline="\n")
    print(f"{len(rows)} zones (tzdata {tzdata.IANA_VERSION}) -> "
          f"{HEADER.relative_to(ROOT)}, {SOURCE.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
